/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserId = IDL.Text;
export const SessionId = IDL.Text;
export const Time = IDL.Int;
export const Message = IDL.Record({
  'content' : IDL.Text,
  'sender' : UserId,
  'timestamp' : Time,
});
export const Stats = IDL.Record({
  'onlineUsers' : IDL.Nat,
  'waitingUsers' : IDL.Nat,
});
export const Gender = IDL.Variant({ 'female' : IDL.Null, 'male' : IDL.Null });
export const QueueResult = IDL.Variant({
  'matched' : SessionId,
  'waiting' : IDL.Null,
});

export const idlService = IDL.Service({
  'checkMatch' : IDL.Func([UserId], [IDL.Opt(SessionId)], ['query']),
  'cleanupStale' : IDL.Func([], [], []),
  'disconnect' : IDL.Func([SessionId, UserId], [], []),
  'getMessages' : IDL.Func([SessionId, Time], [IDL.Vec(Message)], ['query']),
  'getStats' : IDL.Func([], [Stats], ['query']),
  'heartbeat' : IDL.Func([UserId, Gender], [], []),
  'joinQueue' : IDL.Func([UserId, Gender, Gender], [QueueResult], []),
  'leaveQueue' : IDL.Func([UserId], [], []),
  'sendMessage' : IDL.Func([SessionId, UserId, IDL.Text], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserId = IDL.Text;
  const SessionId = IDL.Text;
  const Time = IDL.Int;
  const Message = IDL.Record({
    'content' : IDL.Text,
    'sender' : UserId,
    'timestamp' : Time,
  });
  const Stats = IDL.Record({
    'onlineUsers' : IDL.Nat,
    'waitingUsers' : IDL.Nat,
  });
  const Gender = IDL.Variant({ 'female' : IDL.Null, 'male' : IDL.Null });
  const QueueResult = IDL.Variant({
    'matched' : SessionId,
    'waiting' : IDL.Null,
  });
  
  return IDL.Service({
    'checkMatch' : IDL.Func([UserId], [IDL.Opt(SessionId)], ['query']),
    'cleanupStale' : IDL.Func([], [], []),
    'disconnect' : IDL.Func([SessionId, UserId], [], []),
    'getMessages' : IDL.Func([SessionId, Time], [IDL.Vec(Message)], ['query']),
    'getStats' : IDL.Func([], [Stats], ['query']),
    'heartbeat' : IDL.Func([UserId, Gender], [], []),
    'joinQueue' : IDL.Func([UserId, Gender, Gender], [QueueResult], []),
    'leaveQueue' : IDL.Func([UserId], [], []),
    'sendMessage' : IDL.Func([SessionId, UserId, IDL.Text], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };