/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Gender = { 'female' : null } |
  { 'male' : null };
export interface Message {
  'content' : string,
  'sender' : UserId,
  'timestamp' : Time,
}
export type QueueResult = { 'matched' : SessionId } |
  { 'waiting' : null };
export type SessionId = string;
export interface Stats { 'onlineUsers' : bigint, 'waitingUsers' : bigint }
export type Time = bigint;
export type UserId = string;
export interface _SERVICE {
  'checkMatch' : ActorMethod<[UserId], [] | [SessionId]>,
  'cleanupStale' : ActorMethod<[], undefined>,
  'disconnect' : ActorMethod<[SessionId, UserId], undefined>,
  'getMessages' : ActorMethod<[SessionId, Time], Array<Message>>,
  'getStats' : ActorMethod<[], Stats>,
  'heartbeat' : ActorMethod<[UserId, Gender], undefined>,
  'joinQueue' : ActorMethod<[UserId, Gender, Gender], QueueResult>,
  'leaveQueue' : ActorMethod<[UserId], undefined>,
  'sendMessage' : ActorMethod<[SessionId, UserId, string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];