/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type UserId = string;
export type Time = bigint;
export interface Stats {
    onlineUsers: bigint;
    waitingUsers: bigint;
}
export interface Message {
    content: string;
    sender: UserId;
    timestamp: Time;
}
export type SessionId = string;
export type QueueResult = {
    __kind__: "matched";
    matched: SessionId;
} | {
    __kind__: "waiting";
    waiting: null;
};
export enum Gender {
    female = "female",
    male = "male"
}
export interface backendInterface {
    checkMatch(userId: UserId): Promise<SessionId | null>;
    cleanupStale(): Promise<void>;
    disconnect(sessionId: SessionId, userId: UserId): Promise<void>;
    getMessages(sessionId: SessionId, since: Time): Promise<Array<Message>>;
    getStats(): Promise<Stats>;
    heartbeat(userId: UserId, ownGender: Gender): Promise<void>;
    joinQueue(userId: UserId, ownGender: Gender, preference: Gender): Promise<QueueResult>;
    leaveQueue(userId: UserId): Promise<void>;
    sendMessage(sessionId: SessionId, userId: UserId, text: string): Promise<boolean>;
}
import type { Gender as _Gender, QueueResult as _QueueResult, SessionId as _SessionId } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async checkMatch(arg0: UserId): Promise<SessionId | null> {
        if (this.processError) {
            try {
                const result = await this.actor.checkMatch(arg0);
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkMatch(arg0);
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async cleanupStale(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.cleanupStale();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cleanupStale();
            return result;
        }
    }
    async disconnect(arg0: SessionId, arg1: UserId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.disconnect(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.disconnect(arg0, arg1);
            return result;
        }
    }
    async getMessages(arg0: SessionId, arg1: Time): Promise<Array<Message>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMessages(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMessages(arg0, arg1);
            return result;
        }
    }
    async getStats(): Promise<Stats> {
        if (this.processError) {
            try {
                const result = await this.actor.getStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStats();
            return result;
        }
    }
    async heartbeat(arg0: UserId, arg1: Gender): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.heartbeat(arg0, to_candid_Gender_n2(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.heartbeat(arg0, to_candid_Gender_n2(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async joinQueue(arg0: UserId, arg1: Gender, arg2: Gender): Promise<QueueResult> {
        if (this.processError) {
            try {
                const result = await this.actor.joinQueue(arg0, to_candid_Gender_n2(this._uploadFile, this._downloadFile, arg1), to_candid_Gender_n2(this._uploadFile, this._downloadFile, arg2));
                return from_candid_QueueResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.joinQueue(arg0, to_candid_Gender_n2(this._uploadFile, this._downloadFile, arg1), to_candid_Gender_n2(this._uploadFile, this._downloadFile, arg2));
            return from_candid_QueueResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async leaveQueue(arg0: UserId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.leaveQueue(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.leaveQueue(arg0);
            return result;
        }
    }
    async sendMessage(arg0: SessionId, arg1: UserId, arg2: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.sendMessage(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendMessage(arg0, arg1, arg2);
            return result;
        }
    }
}
function from_candid_QueueResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _QueueResult): QueueResult {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SessionId]): SessionId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    matched: _SessionId;
} | {
    waiting: null;
}): {
    __kind__: "matched";
    matched: SessionId;
} | {
    __kind__: "waiting";
    waiting: null;
} {
    return "matched" in value ? {
        __kind__: "matched",
        matched: value.matched
    } : "waiting" in value ? {
        __kind__: "waiting",
        waiting: value.waiting
    } : value;
}
function to_candid_Gender_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Gender): _Gender {
    return to_candid_variant_n3(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Gender): {
    female: null;
} | {
    male: null;
} {
    return value == Gender.female ? {
        female: null
    } : value == Gender.male ? {
        male: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
